### ISSUE TITLE
UIRibbon shrinks when high dpi support is enabled in application settings

### ISSUE THREAD

**Issue by karooma** [TurboPack/RibbonFramework#56]
The ribbon height and font size shrink when high dpi support is enabled in delphi 10.1 berlin, see following images:

**Resolution 1920 x 1080 - high dpi 100%  zoom**

![1920 x1080 - high dpi 100 zoom](https://cloud.githubusercontent.com/assets/20535050/17921344/5326325e-69d1-11e6-824e-c27d17c4ef1a.png)

**Resolution 1920 x 1080 - high dpi 125%  zoom**

![1920 x1080 - high dpi 125 zoom](https://cloud.githubusercontent.com/assets/20535050/17921345/532880ea-69d1-11e6-99b4-61e24392a133.png)

**Resolution 1920 x 1080 - high dpi support off 100%  zoom**

![1920 x 1080 - no high dpi support 100 zoom](https://cloud.githubusercontent.com/assets/20535050/17921342/532116c0-69d1-11e6-9b55-de3ba17eb232.png)

**Resolution 1920 x 1080 - high dpi support off 125%  zoom**

![1920 x 1080 - no high dpi support 125 zoom](https://cloud.githubusercontent.com/assets/20535050/17921343/53227d94-69d1-11e6-9e5d-06bdd9f24c2a.png)

Cheers.

**Comment by joachimmarder** [comment]
I think I never observed this in our projects. Can this be reproduced with one of the included sample projects?

It seems that the rest  of your application does not scale at all. What setting do you have in you manifest for high-dpi?

**Comment by karooma** [comment]
> I think I never observed this in our projects. Can this be reproduced with one of the included sample projects?

Same problem with textpad sample, using auto generate manifest setting for the application. 
The screen shot shows Windows Explorer, paint and the Textpad sample side by side. 
Paint seems to be not dpi aware while Explorer is indeed scaling well.

![high dpi comparison](https://cloud.githubusercontent.com/assets/20535050/17997199/fc90a196-6b64-11e6-8a0a-70fe0cd570d4.png)

> But it seems that the rest of your application does not scale at all. What setting do you have for the Scaled property in your form?

Scaled is set to true and high dpi handling is fine so far.

**Comment by joachimmarder** [comment]
I was not able to reproduce the issue using this repro steps:
  * Set Windows 10 to 150% in display settings
  * Log off and on again
  * Open "Samples\High Level\07 Text Pad with Action List\TextPad.dproj"
  * Turn on Delphi project option "Application\Manifest File\Enable High dpi" for all 32Bit builds
  * Compile and run

As you can see, everything looks as expected:
<img width="485" alt="2016-08-26 19_33_56-text pad" src="https://cloud.githubusercontent.com/assets/10615289/18014739/986ddf34-6bc4-11e6-883f-764878a0c25b.png">

This includes Windows Paint, which scales on my system. So I guess there must be something wrong with your Windows, I am pretty sure the problem is not within our wrapper for the Windows Ribbon Framework.
